# NumPy Tutorial

> This Jupyter Notebook was created to study the basics aspects of NumPy library and was based in the tutorial available in [SciPy.org](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html) website.
> 
> In this tutorial just the basic operations are shown.


>* **Author:** Gustavo G. Ribeiro
>* **Date:** 27/07/2017


---------------------------------

In [1]:
import numpy as np

-----------------
### The Basics
* Creating an array of 3 integer components with *rank* 1.

In [2]:
a = np.array([1,2,1])
print(a)

[1 2 1]


* Creating an array of 6 float components with *rank* 2.

In [3]:
b = np.array([[1., 0., 0. ],
     [0., 1., 2.]])
print(b)

[[ 1.  0.  0.]
 [ 0.  1.  2.]]


* Function `ndim`  returns the _rank_ from NumPy array.

In [4]:
print( 'Dimension of (a):',a.ndim,', and of (b):',b.ndim )

Dimension of (a): 1 , and of (b): 2


* Function `shape` returns the numbers of columns and rows from NumPy array.

In [5]:
print( 'Shape of (a):',a.shape,', and of (b):',b.shape )

Shape of (a): (3,) , and of (b): (2, 3)


* Function `size` returns the total number of elements of the array.

In [6]:
print( 'Size of (a):',a.size,', and of (b):',b.size )

Size of (a): 3 , and of (b): 6


* Function `dtype` returns the type of the elements of the array.
* Function `itemsize` returns the size in bytes of each element of the array.

In [7]:
print( 'Type:', a.dtype, "\nSize(Bytes):", a.itemsize)

Type: int32 
Size(Bytes): 4


In [8]:
print( 'Type:', b.dtype, "\nSize(Bytes):", b.itemsize)

Type: float64 
Size(Bytes): 8


--------------------
### Array creation
* There are three special functions to create an array filled.
    * Function `zeros`: An array filled by zeros.
    * Function `ones`: An array filled by ones.
    * Function `empty`: An array filled by random numbers from the memory state.

In [9]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.ones( (2,3,4), dtype=np.int16 ) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.empty( (2,3) )  # uninitialized, output may vary

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

* Function `np.arange` allows to create an array filled by a sequence of numbers
    ```Python
    np.arange(initial value, final value, step)
    ```

In [12]:
 np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

* Function `np.linspace` allows to create an array filled by a sequence of numbers, specifying the number of elements
    ```Python
    np.linspace(initial value, final value, number of elements)
    ```

In [13]:
np.linspace( 0, 2, 9 )  

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [14]:
from numpy import pi
x = np.linspace( 0, 2*pi, 30 ) # useful to evaluate function at lots of points
print(x)

[ 0.          0.21666156  0.43332312  0.64998469  0.86664625  1.08330781
  1.29996937  1.51663094  1.7332925   1.94995406  2.16661562  2.38327719
  2.59993875  2.81660031  3.03326187  3.24992343  3.466585    3.68324656
  3.89990812  4.11656968  4.33323125  4.54989281  4.76655437  4.98321593
  5.1998775   5.41653906  5.63320062  5.84986218  6.06652374  6.28318531]


----------------------------
### Basic Operations

* The **elementary arithmetic operators** on arrays apply to all elements (between scalar and array) and element by element (between arrays).

In [15]:
a = np.arange(2,8,1.5)
a

array([ 2. ,  3.5,  5. ,  6.5])

In [16]:
b = np.arange(8,2,-1.5)
b

array([ 8. ,  6.5,  5. ,  3.5])

In [17]:
b-a  # Subtraction

array([ 6.,  3.,  0., -3.])

In [18]:
a+b # Sum

array([ 10.,  10.,  10.,  10.])

In [19]:
a**2 # Power

array([  4.  ,  12.25,  25.  ,  42.25])

In [20]:
5*b # Product

array([ 40. ,  32.5,  25. ,  17.5])

* Also, it is possible to make some **logical operations**.

In [21]:
a<5

array([ True,  True, False, False], dtype=bool)

In [22]:
a>5

array([False, False, False,  True], dtype=bool)

In [23]:
b>a

array([ True,  True, False, False], dtype=bool)

In [24]:
b<a

array([False, False, False,  True], dtype=bool)

* To perform **matrix-matrix product** we should be aware of the different types of product.

In [25]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

1. Element by element product ( *elementwise* )

In [26]:
A*B

array([[2, 0],
       [0, 4]])

2. Matrix product (usual matrix-matrix)

In [27]:
A.dot(B)      # One way to perform

array([[5, 4],
       [3, 4]])

In [28]:
np.dot(A, B)   # Another way to perform

array([[5, 4],
       [3, 4]])

* Operators to **modify** the array

In [29]:
a *= 3
a

array([  6. ,  10.5,  15. ,  19.5])

In [30]:
b += a
b

array([ 14.,  17.,  20.,  23.])

In [31]:
b -= 14
b

array([ 0.,  3.,  6.,  9.])

* **Unary operators**

In [32]:
a.sum()

51.0

In [33]:
a.min()

6.0

In [34]:
a.max()

19.5

In [35]:
print(A)
A.sum(axis=0)

[[1 1]
 [0 1]]


array([1, 2])

In [36]:
print(B) 
B.cumsum() #Cumulative sum along array

[[2 0]
 [3 4]]


array([2, 2, 5, 9], dtype=int32)

* **Universal functions**. These functions operate _elementwise_ on array

In [37]:
np.exp(a)

array([  4.03428793e+02,   3.63155027e+04,   3.26901737e+06,
         2.94267566e+08])

In [38]:
np.sin(a)

array([-0.2794155 , -0.87969576,  0.65028784,  0.60553987])

In [39]:
np.cos(a)

array([ 0.96017029, -0.47553693, -0.75968791,  0.79581497])

In [40]:
np.sqrt(a)

array([ 2.44948974,  3.24037035,  3.87298335,  4.41588043])

In [41]:
print('A:', A)
print('B:', B)
np.add(B, A)

A: [[1 1]
 [0 1]]
B: [[2 0]
 [3 4]]


array([[3, 1],
       [3, 5]])